//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SphereServerScriptAnalyser.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SphereServerScriptAnalyser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Analysis completed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AnalysisCompleted {
            get {
                return ResourceManager.GetString("AnalysisCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not open file: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string CouldNotOpenFile {
            get {
                return ResourceManager.GetString("CouldNotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Files were examined. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string FilesWereExamined {
            get {
                return ResourceManager.GetString("FilesWereExamined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Issue benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No folder selected. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoFolderSelected {
            get {
                return ResourceManager.GetString("NoFolderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open the file benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OpenTheFile {
            get {
                return ResourceManager.GetString("OpenTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Problems were found in {0} files. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ProblemsWereFoundInFiles0 {
            get {
                return ResourceManager.GetString("ProblemsWereFoundInFiles0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Re-Scan benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Rescan {
            get {
                return ResourceManager.GetString("Rescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restart Required benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scanning... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scanning error: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ScanningError {
            get {
                return ResourceManager.GetString("ScanningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the Sphere scripts folder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string SelectTheSphereScriptsFolder {
            get {
                return ResourceManager.GetString("SelectTheSphereScriptsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a valid folder. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string StringAValidFolder {
            get {
                return ResourceManager.GetString("StringAValidFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file could not be read: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TheFileCouldNotBeRead {
            get {
                return ResourceManager.GetString("TheFileCouldNotBeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The folder path is incorrect. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TheFolderPathIsIncorrect {
            get {
                return ResourceManager.GetString("TheFolderPathIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no [eof] at the end of the file. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ThereIsNoEofAtTheEndOfTheFile {
            get {
                return ResourceManager.GetString("ThereIsNoEofAtTheEndOfTheFile", resourceCulture);
            }
        }
    }
}
